[tool.black]
line-length = 110
target-version = ["py38", "py39", "py310"]
skip-string-normalization = true

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = false
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
ignore_missing_imports = true

[tool.isort]
profile = "black"
add_imports = "from __future__ import annotations"

[tool.pydocstyle]
convention = "numpy"
add-ignore = "D100,D101,D102,D103,D104,D107,D203,D213"

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "missing-docstring",
  "line-too-long",
  "too-many-locals",
  "pointless-statement",
  "import-outside-toplevel",
  "invalid-name",
  "expression-not-assigned",
  "too-many-arguments",
]
[tool.pylint.'MISCELLANEOUS']
notes=["FIXME","XXX"]  # ignore TODO tag
